name: Start get your own free ArchLinux.cyou subdomain
description: Choose this if you are applying for a free ArchLinux.cyou subdomain for the first time
labels: ["Applying"]
assignees:
  - linlinzzo
body:
  - type: markdown
    attributes:
      value: |
        Please write "your website name" in the title!
  - type: input
    id: name
    attributes:
      label: The website name
      description: will show it in README.md
      placeholder: ex. My blog
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: The website address or IP
      description: |
        For resolving domain names
      placeholder: ex. https://wow.github.io or 1.1.1.1
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Are you a Arch Linux user?
      description: |
        Please show your screenshots
    validations:
      required: false
  - type: checkboxes
    id: checkagain
    attributes:
      label: Warning
      description: |
        As the owner of the repository, you keep complete control over your published content. But that also means that all rights and duties that come along with publishing a website remain in your responsibility.
      options:
        - label: I know that
          required: true
